# Спецификация к Лабораторной работе №11 

# Процедуры и функции. 
# Поиск экстремума среди трех значений
# (Вариант 22)

## Абстракция А0
### 1. Постановка задачи.
#### Задание: 
Написать две программы обработки трех двухмерных массивов.

В первой версии программы использовать только процедуры общего вида. 

Во второй версии программы должна быть хотя бы одна функция. 

#### Условие: 
Найти сумму элементов для каждой из трех матриц.

Для каждой из матриц сформировать одномерный массив, 

авный по длине количеству строк матрицы и содержащий значения 0 или 1:

- 1, если в соответствующей строке элемент на главной диагонали больше других элементов этой строки;

- 0, если это условие для данной строки не выполняется.

Определить матрицу с максимальной суммой элементов.

### 2. Уточненная постановка задачи.
Даны матрицы $A, B, C$ с размерностями $n_A \times n_A, \ n_B \times n_B, \ n_C \times n_C$ .

Получить три массива $\{X_1, X_2, ..., X_{n_A}\}, \{X_1, X_2, ..., X_{n_B}\}, \{X_1, X_2, ..., X_{n_C}\}$ по правилу:
    
$\large{\displaystyle{X_i = \begin{cases}
1, \ Y_{ii} > Y_{ij}, \ \forall j: 0<j<n_Y+1 \land j \neq i\\
0, \ Y_{ii} \leq Y_{ij}, \ \forall j: 0<j<n_Y+1 \land j \neq i\\
\end{cases}, \ \forall i: 0<i<n_Y+1, \ \forall Y \in \{A, B, C\} }}$

Найти $\large{\displaystyle{S_Y = \sum_{\substack{0<i<n_Y+1 \\ 0<j<n_Y+1}} Y_{ij}, \ \forall Y \in \{A, B, C\} }}$

### 3. Пример с иллюстрацией.

In [3]:
import numpy
import pylab 
%matplotlib inline
pylab.style.use('seaborn-whitegrid')

In [34]:
def write_txt(file_name, A, B, C):
    with open(file_name, 'w') as f:
        for Y in [A, B, C]:
            f.write("{}\n".format(Y.shape[0]))
            for i in range(Y.shape[0]):
                f.write("{}\n".format(Y[i]))
                
def read_txt(file_name):
    with open(file_name, 'r') as f:
        Y = f.readlines()
    NA = int(Y[0]); NB = int(Y[NA+1]); NC = int(Y[NA+NB+2])
    A = [x[1:-2].split() for x in Y[1:NA+1]]
    A = [[int(x) for x in A[i]] for i in range(NA)]
    B = [x[1:-2].split() for x in Y[NA+2:NA+NB+2]]
    B = [[int(x) for x in B[i]] for i in range(NB)]
    C = [x[1:-2].split() for x in Y[NA+NB+3:]]
    C = [[int(x) for x in C[i]] for i in range(NC)]
    return (NA, NB, NC, A, B, C)

In [35]:
A1 = numpy.random.randint(-100, 100, size=(5,5))
B1 = numpy.random.randint(-100, 100, size=(4,4))
C1 = numpy.random.randint(-100, 100, size=(5,5))
print('\n', A1, '\n\n', B1, '\n\n', C1)
write_txt('ABC_Lab11_1.txt', A1, B1, C1)


 [[ -66   29   -2    6  -99]
 [  92   43 -100   97   -5]
 [  72  -52  -65   33  -26]
 [  82  -49  -79  -55  -14]
 [ -44   53  -19  -29   42]] 

 [[-34  -9 -97  48]
 [-63 -21  47   0]
 [ 20  92  18  18]
 [-80 -76 -26  25]] 

 [[ 50  47 -25  34 -15]
 [-50  57 -20  71  70]
 [ -7  96  66 -89 -46]
 [ 93 -39   1  64  27]
 [ 51  45 -95 -55  80]]


In [36]:
NA, NB, NC, A, B, C = read_txt('ABC_Lab11_1.txt')
print(NA, NB, NC, '\n\n', A, '\n\n', B, '\n\n', C)

5 4 5 

 [[-66, 29, -2, 6, -99], [92, 43, -100, 97, -5], [72, -52, -65, 33, -26], [82, -49, -79, -55, -14], [-44, 53, -19, -29, 42]] 

 [[-34, -9, -97, 48], [-63, -21, 47, 0], [20, 92, 18, 18], [-80, -76, -26, 25]] 

 [[50, 47, -25, 34, -15], [-50, 57, -20, 71, 70], [-7, 96, 66, -89, -46], [93, -39, 1, 64, 27], [51, 45, -95, -55, 80]]
