# Спецификация к Лабораторной работе №9 

# Поиск строки или столбца матрицы по условию. 
# Обработка исключений.

# (Вариант 22)

## Абстракция А0
### 1. Постановка задачи.
#### Задание: 
Написать программу обработки матрицы в соответствии с условием. 

#### Условие: 
Проанализировать матрицу. 

Проверить, все ли столбцы матрицы упорядочены по неубыванию.

Если не все, сообщить номер последнего неупорядоченного.

### 2. Уточненная постановка задачи.
Дана матрица $A$, состоящая из n строк и m столбцов. 

Проанализировать столбцы с номерами $i \in \{1, ..., m\}$,

выполняется ли условие $A_{1i} \leq A_{2i} \leq  ... \leq A_{ni} (*)$

Если не для всех, сообщить наибольший номер $N$ столбца, 

для которого $(*)$ не выполняется.

### 3. Пример с иллюстрацией.

In [1]:
import numpy
import pylab 
%matplotlib inline
pylab.style.use('seaborn-whitegrid')

In [57]:
A1 = numpy.random.randint(-100, 100, size=(4,5))
numpy.savetxt('A_Lab9_1.txt', A1, fmt='%5.0f')
print(A1)

[[ 96 -88  31 -33  95]
 [ 24 -36  73  23 -92]
 [ 24 -32  33 -77  42]
 [ 18 -38  63  42  15]]


In [58]:
A2 = numpy.random.randint(0, 2, size=(3,5))
numpy.savetxt('A_Lab9_2.txt', A2, fmt='%5.0f')
print(A2, '\n\n', A2.shape)

[[1 0 0 1 1]
 [0 0 1 1 0]
 [0 0 0 0 0]] 

 (3, 5)


In [59]:
A2 == numpy.sort(A2, axis=0)

array([[False,  True,  True, False, False],
       [ True,  True, False,  True,  True],
       [False,  True, False, False, False]])

In [60]:
numpy.sum(A2 == numpy.sort(A2, axis=0), axis=0)

array([1, 3, 1, 1, 1])

In [61]:
numpy.sum(A2 == numpy.sort(A2, axis=0), axis=0) < A2.shape[0]

array([ True, False,  True,  True,  True])

In [62]:
sum(numpy.sum(A2 == numpy.sort(A2, axis=0), axis=0) < A2.shape[0]) != 0 

True

In [63]:
numpy.nonzero(numpy.sum(A2 == numpy.sort(A2, axis=0), axis=0) < A2.shape[0])[0][-1] + 1

5

In [64]:
A3 = numpy.random.randint(0, 5, size=(3,5))
numpy.savetxt('A_Lab9_3.txt', A3, fmt='%5.0f')
print(A3, '\n\n', A3.shape)

[[4 0 2 2 3]
 [0 3 1 3 4]
 [0 2 1 4 3]] 

 (3, 5)


In [65]:
print(20*' ' + 'Лаб.9\n' + 90*'=')

# fin = str(input('Текстовый файл с элементами матрицы A: '))
# fout = str(input('Текстовый файл с элементами матрицы A и номером столбца N: '))

print(90*'=' + '\n' + 'Исходная матрица A: \n')
A = numpy.loadtxt('A_Lab9_1.txt', dtype='int')
print(A)

if sum(numpy.sum(A == numpy.sort(A, axis=0), axis=0) < A.shape[0]) != 0:
    N = numpy.nonzero(numpy.sum(A == numpy.sort(A, axis=0), axis=0) < A.shape[0])[0][-1] + 1

    print(90*'=' + '\n' + 'Наибольший номер неупорядоченного столбца N (по неубыванию): \n')
    print(N)
else:
    print(90*'=' + '\n' + 'Все столбцы матрицы сортированы по неубыванию)')

                    Лаб.9
Исходная матрица A: 

[[ 96 -88  31 -33  95]
 [ 24 -36  73  23 -92]
 [ 24 -32  33 -77  42]
 [ 18 -38  63  42  15]]
Наибольший номер неупорядоченного столбца N (по неубыванию): 

5
