# Спецификация к Лабораторной работе №11 

# Процедуры и функции. 
# Поиск экстремума среди трех значений
# (Вариант 22)

## Абстракция А0
### 1. Постановка задачи.
#### Задание: 
Написать две программы обработки трех двумерных массивов.

В первой версии программы использовать только процедуры общего вида. 

Во второй версии программы должна быть хотя бы одна функция. 

#### Условие: 
Найти сумму элементов для каждой из трех матриц.

Для каждой из матриц сформировать одномерный массив, 

равный по длине количеству строк матрицы и содержащий значения 0 или 1:

- 1, если в соответствующей строке элемент на главной диагонали больше других элементов этой строки;

- 0, если это условие для данной строки не выполняется.

Определить матрицу с максимальной суммой элементов.

### 2. Уточненная постановка задачи.
Даны матрицы $A, B, C$ с размерностями $n_A \times n_A, \ n_B \times n_B, \ n_C \times n_C$ .

Получить три массива $\{X_1, X_2, ..., X_{n_A}\}, \{X_1, X_2, ..., X_{n_B}\}, \{X_1, X_2, ..., X_{n_C}\}$ по правилу:
    
$\large{\displaystyle{X_i = \begin{cases}
1, \ Y_{ii} > Y_{ij}, \ \forall j: 0<j<n_Y+1 \land j \neq i\\
0, \ Y_{ii} \leq Y_{ij}, \ \forall j: 0<j<n_Y+1 \land j \neq i\\
\end{cases}, \ \forall i: 0<i<n_Y+1, \ \forall Y \in \{A, B, C\} }}$.

Найти $\large{\displaystyle{S_Y = \sum_{\substack{0<i<n_Y+1 \\ 0<j<n_Y+1}} Y_{ij}, \ \forall Y \in \{A, B, C\} }}$.

Определить $\large{\displaystyle{\max_{Y \in \{A, B, C\}} S_Y }}$.

### 3. Пример с иллюстрацией.

In [1]:
import numpy
import pylab 
%matplotlib inline
pylab.style.use('seaborn-whitegrid')

In [2]:
def write_datatxt(file_name, A, B, C):
    with open(file_name, 'w') as f:
        for Y in [A, B, C]:
            f.write("{}\n".format(Y.shape[0]))
            for i in range(Y.shape[0]):
                f.write("{}\n".format(Y[i]))

In [3]:
A1 = numpy.random.randint(-100, 100, size=(5,5))
B1 = numpy.random.randint(-100, 100, size=(4,4))
C1 = numpy.random.randint(-100, 100, size=(5,5))
print('\n', A1, '\n\n', B1, '\n\n', C1)
write_datatxt('ABC_Lab11_1.txt', A1, B1, C1)


 [[-66 -32   2  64  23]
 [-31 -29 -65  88  12]
 [-22  61 -26  55 -17]
 [-29 -42 -59 -54 -27]
 [ -5 -42 -22 -53  36]] 

 [[ -5 -34 -58 -38]
 [ 36 -57  97   7]
 [-95  25 -76  40]
 [-90  85 -73 -60]] 

 [[-46 -76  -5  58  73]
 [-13  62 -53 -58 -89]
 [ -9  27 -80  30  21]
 [-20 -75  33 -24 -15]
 [ 41  73 -95  18 -64]]


In [8]:
# Версия 1
print(20*' ' + 'Лаб.11\n' + 90*'=')

fin = str(input('Текстовый файл с элементами исходных матриц: '))
fout = str(input('Текстовый файл с элементами исходных матриц и результатами: '))
                
with open(fin, 'r') as f:
    Y = f.readlines()
NA = int(Y[0]); NB = int(Y[NA+1]); NC = int(Y[NA+NB+2])
A = [x[1:-2].split() for x in Y[1:NA+1]]
A = [[int(x) for x in A[i]] for i in range(NA)]
B = [x[1:-2].split() for x in Y[NA+2:NA+NB+2]]
B = [[int(x) for x in B[i]] for i in range(NB)]
C = [x[1:-2].split() for x in Y[NA+NB+3:]]
C = [[int(x) for x in C[i]] for i in range(NC)]
N = [NA, NB, NC]; Y = [A, B, C]; L = ['A', 'B', 'C']

X, S = 3 * [[0]], 3 * [0]
for k in range(3):
    X[k] = [int(sum([int(Y[k][j][i] < Y[k][i][i]) \
            for j in range(len(Y[k][i]))]) == len(Y[k]) - 1) \
            for i in range(len(Y[k]))]
    S[k] = sum([sum(Y[k][i]) for i in range(len(Y[k]))])
K = S.index(max(S))

print(90*'=' + '\n')
for i in range(3):
    print('Матрица ', L[i], ': \n')
    for j in range(N[i]):
        print(Y[i][j])
    print('\n' + 'Массив X{}: \n'.format(L[i]))
    print(X[i])
    print('\n' + 'Сумма элементов S{}: {}\n'.format(L[i], S[i]))
    print(90*'=' + '\n')
print('\n' + 'Матрица с максимальной суммой элементов: {}\n'.format(L[K]))

with open(fout, 'w') as f:        
    for i in range(3):
        f.write("{}\n".format(N[i]))
        for j in range(len(Y[i])):
            f.write("{}\n".format(Y[i][j]))
        f.write("{}\n".format(X[i]))
        f.write("{}\n".format(S[i]))     
    f.write("{}\n".format(L[K]))

                    Лаб.11
Текстовый файл с элементами исходных матриц: ABC_Lab11_1.txt
Текстовый файл с элементами исходных матриц и результатами: ABCXS_Lab11_1.txt

Матрица  A : 

[-66, -32, 2, 64, 23]
[-31, -29, -65, 88, 12]
[-22, 61, -26, 55, -17]
[-29, -42, -59, -54, -27]
[-5, -42, -22, -53, 36]

Массив XA: 

[0, 0, 0, 0, 1]

Сумма элементов SA: -280


Матрица  B : 

[-5, -34, -58, -38]
[36, -57, 97, 7]
[-95, 25, -76, 40]
[-90, 85, -73, -60]

Массив XB: 

[0, 0, 0, 0]

Сумма элементов SB: -296


Матрица  C : 

[-46, -76, -5, 58, 73]
[-13, 62, -53, -58, -89]
[-9, 27, -80, 30, 21]
[-20, -75, 33, -24, -15]
[41, 73, -95, 18, -64]

Массив XC: 

[0, 0, 0, 0, 0]

Сумма элементов SC: -286



Матрица с максимальной суммой элементов: A



In [9]:
# Версия 2
print(20*' ' + 'Лаб.11\n' + 90*'=')

fin = str(input('Текстовый файл с элементами исходных матриц: '))
fout = str(input('Текстовый файл с элементами исходных матриц и результатами: '))
                
def read_txt(file_name):
    with open(file_name, 'r') as f:
        Y = f.readlines()
    NA = int(Y[0]); NB = int(Y[NA+1]); NC = int(Y[NA+NB+2])
    A = [x[1:-2].split() for x in Y[1:NA+1]]
    A = [[int(x) for x in A[i]] for i in range(NA)]
    B = [x[1:-2].split() for x in Y[NA+2:NA+NB+2]]
    B = [[int(x) for x in B[i]] for i in range(NB)]
    C = [x[1:-2].split() for x in Y[NA+NB+3:]]
    C = [[int(x) for x in C[i]] for i in range(NC)]
    N = [NA, NB, NC]; Y = [A, B, C]; L = ['A', 'B', 'C']
    return N, Y, L
                
def find_XSK(Y):
    X, S = 3 * [[0]], 3 * [0]
    for k in range(3):
        X[k] = [int(sum([int(Y[k][j][i] < Y[k][i][i]) \
               for j in range(len(Y[k][i]))]) == len(Y[k]) - 1) \
               for i in range(len(Y[k]))]
        S[k] = sum([sum(Y[k][i]) for i in range(len(Y[k]))])
    K = S.index(max(S))
    return X, S, K

def write_txt(file_name, N, Y, L, X, S, K):
    with open(file_name, 'w') as f:        
        for i in range(3):
            f.write("{}\n".format(N[i]))
            for j in range(len(Y[i])):
                f.write("{}\n".format(Y[i][j]))
            f.write("{}\n".format(X[i]))
            f.write("{}\n".format(S[i]))     
        f.write("{}\n".format(L[K]))

N, Y, L = read_txt(fin)
X, S, K = find_XSK(Y)

print(90*'=' + '\n')
for i in range(3):
    print('Матрица ', L[i], ': \n')
    for j in range(N[i]):
        print(Y[i][j])
    print('\n' + 'Массив X{}: \n'.format(L[i]))
    print(X[i])
    print('\n' + 'Сумма элементов S{}: {}\n'.format(L[i], S[i]))
    print(90*'=' + '\n')
print('\n' + 'Матрица с максимальной суммой элементов: {}\n'.format(L[K]))  

write_txt(fout, N, Y, L, X, S, K)

                    Лаб.11
Текстовый файл с элементами исходных матриц: ABC_Lab11_1.txt
Текстовый файл с элементами исходных матриц и результатами: ABCXS_Lab11_1.txt

Матрица  A : 

[-66, -32, 2, 64, 23]
[-31, -29, -65, 88, 12]
[-22, 61, -26, 55, -17]
[-29, -42, -59, -54, -27]
[-5, -42, -22, -53, 36]

Массив XA: 

[0, 0, 0, 0, 1]

Сумма элементов SA: -280


Матрица  B : 

[-5, -34, -58, -38]
[36, -57, 97, 7]
[-95, 25, -76, 40]
[-90, 85, -73, -60]

Массив XB: 

[0, 0, 0, 0]

Сумма элементов SB: -296


Матрица  C : 

[-46, -76, -5, 58, 73]
[-13, 62, -53, -58, -89]
[-9, 27, -80, 30, 21]
[-20, -75, 33, -24, -15]
[41, 73, -95, 18, -64]

Массив XC: 

[0, 0, 0, 0, 0]

Сумма элементов SC: -286



Матрица с максимальной суммой элементов: A

