# Спецификация к Типовому расчету
# по дисциплине «Программирование»
# 1 семестр

# (Вариант 22)

## Абстракция А0
### 1. Постановка задачи.
#### Задание: 
Написать программу обработки двух матриц в соответствии с условием.

#### Условие: 
Дана матрица $A$ из $N$ строк и $N$ столбцов. 

Кроме матрицы $A$ дана матрица $B$ такого же размера. 

Если каждый элемент матрицы $A$ больше соответствующего элемента матрицы $B$, 

присвоить элементам $C_1, C_2, ..., C_N$ значения по правилу:

$\displaystyle{C_i = \sum_{k=1}^{N} (A_{ik} + B_{ik}) \ (*)}$

### 2. Уточненная постановка задачи.
Дана две квадратные матрицы $A$ и $B$, состоящие из N строк и N столбцов. 

Сравнить соответствующие элементы матриц $A$ и $B$.

Если $A_{ij} > B_{ij}, \forall i, j: 0 < i < N+1, 0 < j < N+1$, то

сформирмировать одномерный массив $C_1, C_2, ..., C_N$  по правилу $(*)$.

### 3. Пример с иллюстрацией.

In [1]:
import numpy
import pylab 
%matplotlib inline
pylab.style.use('seaborn-whitegrid')

In [4]:
def write_datatxt(file_name, N, A, B):
    with open(file_name, 'w') as f:
        f.write("{}\n".format(N))
        for M in [A, B]:
            for i in range(N):
                f.write("{}\n".format(M[i]))

In [8]:
N = 5
A = numpy.random.randint(0, 100, size=(N,N))
B = numpy.random.randint(-100, 0, size=(N,N))
write_datatxt('AB_SC_1.txt', N, A, B)
print('\n', N, '\n\n', A, '\n\n', B)


 5 

 [[79 21 39 88 16]
 [14 75  0 71  1]
 [33  1 58 73 16]
 [36 54 39 75 83]
 [31  8 92 51 37]] 

 [[-50 -86 -33 -50 -67]
 [-78 -66 -90 -88 -92]
 [-96 -33 -51 -30 -27]
 [-95 -68 -31 -84 -97]
 [-71 -67  -8 -13 -94]]
